lib/vueshatter_web/router.ex
defmodule VueshatterWeb.Router do
  use VueshatterWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", VueshatterWeb do
    pipe_through :browser # Use the default browser stack

    # get "/", PageController, :index
    get "/", BookController, :index
    get "/item/:id", BookController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", VueshatterWeb do
  #   pipe_through :api
  # end
end

lib/vueshatter/application.ex
defmodule Vueshatter.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Vueshatter.Repo, []),
      # Start the endpoint when the application starts
      supervisor(VueshatterWeb.Endpoint, []),
      # Start your own worker by calling: Vueshatter.Worker.start_link(arg1, arg2, arg3)
      # worker(Vueshatter.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Vueshatter.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    VueshatterWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/vueshatter/data_access.ex
defmodule Vueshatter.DataAccess do
  @moduledoc """
  The Accounts context.
  """
  import Ecto.Query, warn: false
  alias Vueshatter.Repo

  # alias Vueshatter.Models.LoanHistory
  alias Vueshatter.Models.Book
  alias Vueshatter.Models.User
  alias Vueshatter.Models.LoanHistory


  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  def create_books(attrs \\ %{}) do
    %Book{}
    |> Book.changeset(attrs)
    |> Repo.insert()
  end

  def create_loans(attrs \\ %{}) do
    %LoanHistory{}
    |> LoanHistory.changeset(attrs)
    |> Repo.insert()
  end

  def select_mybooks(model, my_id) do
    from l in model,
    join: b in Book,
    on: b.id == l.book_id,
    where: l.user_id == ^my_id,
    select: l
  end
  def get_my_books!(my_id) do
    #from(driver_loc in query, where: driver_loc.status == "Invisible", order_by: fragment("? <-> ST_SetSRID(ST_MakePoint(?,?), ?)", driver_loc.driver_lat_long, ^lng, ^lat, ^srid))
    from orders  in LoanHistory , where: orders.user_id == ^my_id
   end

  def my_books!(my_id), do: Repo.get_by(LoanHistory, user_id: my_id)

  def get_loan!(id), do: Repo.get!(LoanHistory, id)
  def get_Book!(id), do: Repo.get!(Book, id)

  def update_loan(%LoanHistory{} = loan, attrs) do
    loan
    |> LoanHistory.changeset(attrs)
    |> Repo.update()
  end


end

lib/vueshatter/repo.ex
defmodule Vueshatter.Repo do
  use Ecto.Repo, otp_app: :vueshatter

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/vueshatter_web/controllers/book_controller.ex
defmodule VueshatterWeb.BookController do
  use VueshatterWeb, :controller
  alias Vueshatter.{Repo, Models.Book, DataAccess, Models.LoanHistory,Model.User}
  # alias Ecto.{Changeset}

  # alias Vueshatter.Models.AuctionItem

  def index(conn, _params) do
    books =  DataAccess.get_my_books!(1)|> Repo.all |> Repo.preload(:book)
   #  IO.puts("==========")
   #  IO.inspect(books)
   #  IO.puts("==========")
    render(conn, "index.html", books: books)
   end

   def show(conn, %{"id" => id}) do
   result = DataAccess.get_loan!(id)
   book = DataAccess.get_Book!(result.id)

   extentionA = %{:return_date => Date.add(result.return_date, 7), :extendedtime => result.extendedtime+1}
   extentionB = %{:return_date => Date.add(result.return_date,14), :extendedtime => result.extendedtime+1}
   extentionC = %{:return_date => Date.add(result.return_date, 21), :extendedtime => result.extendedtime+1}
   if(result.extendedtime < 4 && book.code == "A") do
      with {:ok, %LoanHistory{} = _loan} <- DataAccess.update_loan(result, extentionA) do
         conn |> put_flash(:info, "Extension accepted")
              |> redirect(to: "/")
   end
   else if(result.extendedtime < 4 && book.code == "B") do
   with {:ok, %LoanHistory{} = _loan} <- DataAccess.update_loan(result, extentionB) do
      conn |> put_flash(:info, "Extension accepted")
           |> redirect(to: "/")
end
else if(result.extendedtime < 4 && book.code == "C") do
   with {:ok, %LoanHistory{} = _loan} <- DataAccess.update_loan(result, extentionC) do
      conn |> put_flash(:info, "Extension accepted")
           |> redirect(to: "/")
end
else
   conn
   |> put_flash(:error, "Extension rejected")
   |> redirect(to: "/")
end
#    case result.extendedtime < 4  do
#     true ->
#    with {:ok, %LoanHistory{} = _loan} <- DataAccess.update_loan(result, extentionA) do
#    conn |> put_flash(:info, "Extension accepted")
#         |> redirect(to: "/")
#    end
#   false ->
#      conn
#       |> put_flash(:error, "Extension rejected")
#       |> redirect(to: "/")
#    end
end
end
end
end

lib/vueshatter_web/controllers/page_controller.ex
defmodule VueshatterWeb.PageController do
  use VueshatterWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/vueshatter_web/views/book_view.ex
defmodule VueshatterWeb.BookView do
  use VueshatterWeb, :view
end

lib/vueshatter_web/views/error_view.ex
defmodule VueshatterWeb.ErrorView do
  use VueshatterWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/vueshatter_web/views/layout_view.ex
defmodule VueshatterWeb.LayoutView do
  use VueshatterWeb, :view
end

lib/vueshatter_web/views/page_view.ex
defmodule VueshatterWeb.PageView do
  use VueshatterWeb, :view
end

lib/vueshatter_web/templates/book/index.html.eex
 <table class="table"> 
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Code</th>
      <th scope="col">Start Date</th>
      <th scope="col">Due Date</th>
      <th scope="col">Time extended</th>
      <th scope="col">Extended</th>
    </tr>
  </thead>
  <tbody> 
  <%= for history <- @books do %>
  <tr>
   
    <td><%= history.book.title  %></td>
    <td><%= history.book.code  %></td>
    <td><%= history.start_date %> </td>
    <td><%= history.return_date %> </td>
    <td><%= history.extendedtime %> </td>
    <td class="text-right">
       <%= link "Extend", to: book_path(@conn, :show, history.id), class: "btn btn-default btn-xs"  %>
    </td> 
   </tr>  
<% end %>
  </tbody>
</table>
</div> 

lib/vueshatter_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Vueshatter!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/vueshatter_web/templates/page/index.html.eex
<div id="vue-playground">
  {{ message }}
</div>
<div id="main">
  <hello></hello>
</div>

<h1>Vue-Router playground</h1>
<div id="router-main">
  <router-link to="/my-hello">Hello</router-link>
  |
  <router-link to="/my-world">World</router-link>
  <router-view></router-view>
</div>